# config.yaml
version:
  name: PreventIdleApp
  version: "1.0.0"

scheduler:
  interval: "10"

idlePrevention:
  enabled: true
  interval: "5"      # 模擬操作間隔時間
  mode: "mixed"       # 模擬模式，可選：key, mouse, mixed

logging:
  level: "info"
  output: "console"   # 或指定檔案路徑

retryPolicy:
  maxRetries: 3
  retryInterval: "10"

workSchedule:
  monday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  tuesday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  wednesday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  thursday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  friday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  saturday: []
  sunday: []